name: Deploy Helm Chart to AKS

on:
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub UI
  push:
    branches:
      - main # Runs on every push to main, adjust as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AKS_RESOURCE_GROUP: "your-aks-resource-group-name"
      AKS_CLUSTER_NAME: "your-aks-cluster-name"
      SOURCE_ACR_NAME: "reference"
      DESTINATION_ACR_NAME: "instance"
      DESTINATION_ACR_RG: "instance-acr-rg"
      DESTINATION_SUBSCRIPTION_ID: "c9e7611c-d508-4-f-aede-0bedfabc1560"
      HELM_CHART_NAME: "your-helm-chart-name"
      HELM_CHART_VERSION: "1.0.0"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Configuration
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --overwrite-existing

    - name: Deploy Helm Chart to AKS
      run: |
        helm repo add instance https://${{ env.DESTINATION_ACR_NAME }}.azurecr.io/helm/v1/repo
        helm repo update
        helm install ${{ env.HELM_CHART_NAME }} instance/${{ env.HELM_CHART_NAME }} --version ${{ env.HELM_CHART_VERSION }} --namespace default
